IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID('p_TRANSFERENCIA_BANCARIA_i'))
BEGIN
    DROP PROCEDURE p_TRANSFERENCIA_BANCARIA_i
END
GO
CREATE PROCEDURE p_TRANSFERENCIA_BANCARIA_i
@CONTA_ID_DEBITO INT,
@CONTA_ID_CREDITO INT,
@VALOR DECIMAL
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
			IF NOT EXISTS(SELECT 1 FROM CONTA WHERE CONTA_ID = @CONTA_ID_DEBITO)
				RAISERROR('CONTA NÃO ENCONTRADA!', 11, 1)
			IF NOT EXISTS(SELECT 1 FROM CONTA WHERE CONTA_ID = @CONTA_ID_CREDITO)
				RAISERROR('CONTA NÃO ENCONTRADA!', 11, 1)		

			--SELECT * FROM CONTA WHERE CONTA_ID = @CONTA_ID_DEBITO;
			--SELECT * FROM CONTA WHERE CONTA_ID = @CONTA_ID_CREDITO;

			INSERT INTO CONTA_TRANSACAO (TRANSACAO_DATA, CONTA_id, TRANSACAO_TIPO_COD, 
			QUANTIA, DATA_FUNDO_DISPONIVEL)
			SELECT GETDATE(), @CONTA_ID_DEBITO, 'DEBITO', -@VALOR, GETDATE()

			INSERT INTO CONTA_TRANSACAO (TRANSACAO_DATA, CONTA_id, TRANSACAO_TIPO_COD, 
			QUANTIA, DATA_FUNDO_DISPONIVEL)
			SELECT GETDATE(), @CONTA_ID_CREDITO, 'CREDITO', @VALOR, GETDATE()

			UPDATE CONTA SET SALDO_DISPONIVEL = SALDO_DISPONIVEL - @VALOR WHERE CONTA_ID = @CONTA_ID_DEBITO;
			UPDATE CONTA SET SALDO_DISPONIVEL = SALDO_DISPONIVEL + @VALOR WHERE CONTA_ID = @CONTA_ID_CREDITO;

			--SELECT * FROM CONTA WHERE CONTA_ID = @CONTA_ID_DEBITO;
			--SELECT * FROM CONTA WHERE CONTA_ID = @CONTA_ID_CREDITO;
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRAN

		RAISERROR('ERRO AO TRANSFERIR ENTRE CONTAS!', 1, 1)
	END CATCH

END
GO